### ISSUE TITLE
Conflict with Vue.mixin

### ISSUE THREAD

**Issue by simplesmiler** [rhyzx/vue-transfer-dom#2]
Vue has a syntax for defining global mixins, `Vue.mixin({ ... })`. Some libraries use it to inject global hooks into components.

Now, if `Vue.mixin` was ever applied before `Vue.use(VueTransferDom)`, then a runtime error appears.
But If `Vue.mixin` is applied **after** `Vue.use(VueTransferDom)`, then the error goes away.

Repro: https://jsfiddle.net/ujafg3js/1/

**Comment by rhyzx** [comment]
Thanks for your issue.
After some investigations, i found this is a bug of Vue, i will create a PR for Vue soon.

**Comment by rhyzx** [comment]
Fixed in https://github.com/vuejs/vue/pull/2366

**Comment by simplesmiler** [comment]
:+1:
