### ISSUE TITLE
Attribute "v-transfer-dom" is ignored

### ISSUE THREAD

**Issue by georgecoca** [rhyzx/vue-transfer-dom#5]
I get this warning when using this attribute on production. On local environment I don't see this warnings.

**[Vue warn]: Attribute "v-transfer-dom" is ignored on component <users-information-source-store> because the component is a fragment instance**

I also tried to use it on a root element but then I get this:

**v-transfer-dom="" cannot be used on an instance root element.**

![Image](http://i.imgur.com/FV8opjE.png)

**Comment by rhyzx** [comment]
Hi @geodeveloper did you checked this issue? https://github.com/rhyzx/vue-transfer-dom/issues/1, seems the same problem.

By the way, the latest `vue-transfer-dom`(1.1.0) require vue 1.0.19(not released yet) due to its' new API, if you use `1.1` you should downgrade to `1.0.x` temporary.

**Comment by georgecoca** [comment]
I'm using `1.0.0`. And I've tried to use it on root element but also fragment as you can see on console log. I'm not using `v-if`.

**Comment by georgecoca** [comment]
I installed last version `1.0.19` for vue and it seems the issue has been resolved.
