### ISSUE TITLE
[Feature Request] Support Vue 2

### ISSUE THREAD

**Issue by posva** [rhyzx/vue-transfer-dom#6]
Hello,

Do you have any plans on porting this to Vue 2?

**Comment by tmorehouse** [comment]
I have created a Vue 2 fork at https://github.com/tmorehouse/vue-transfer-dom

**Comment by posva** [comment]
Actually, there's vue-portal now: https://github.com/LinusBorg/portal-vue

**Comment by tmorehouse** [comment]
Very cool.  Will take a look at it.
